package com.example.FileGenerator.EnvFile.Services;

import com.example.FileGenerator.EnvFile.Dto.ReadmeRequestDto;
import org.springframework.stereotype.Service;

@Service

public class ReadmeGenerator {

    public  String createReadme(ReadmeRequestDto readmeRequestDto){

        String content = """
          ProjectName::      %s
          Framework  ::     %s
             Generated by JS Intialization
             
                ## Installation
                
                            ```bash
                            npm install
                            ```
                
                            ## Development
                
                            ```bash
                            npm run dev
                            ```
                
                            ## Production
                
                            ```bash
                            npm start
                            ```
                            
            
                
                
                """.formatted(readmeRequestDto.getProjectName(),readmeRequestDto.getFramework());
        return content;
    }

}
